import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import AuthComponent from "../lib/AuthComponent";
import { Grid } from "@mui/material";
import TradingParameters from "../components/TradingParameters";
import g from "../assets/g.png";
import c from "../assets/c.png";
import e from "../assets/e.png";
import h from "../assets/h.png";
import k from "../assets/k.png";
import f from "../assets/f.png";
import d from "../assets/d.png";
import j from "../assets/j.png";
import i from "../assets/i.png";
import { Box } from "@mui/system";

const Business: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Grid sx={{ mt: 1 }} container spacing={2}>
        <Grid sm={12} md={12} lg={7} xl={8} item>
          <Box sx={{ mb: 2 }}>
            <Image layout="responsive" src={g} alt="fucking image" />
          </Box>
          <Grid container spacing={2}>
            <Grid item xs={12} md={12} lg={6}>
              <Box sx={{ mb: 2 }}>
                <Image layout="responsive" src={c} alt="fucking image" />
              </Box>
              <Box sx={{ mb: 2 }}>
                <Image layout="responsive" src={h} alt="fucking image" />
              </Box>
              <Box sx={{ mb: 2 }}>
                <Image layout="responsive" src={k} alt="fucking image" />
              </Box>
              <Box sx={{ mb: 2 }}>
                <Image layout="responsive" src={i} alt="fucking image" />
              </Box>
            </Grid>
            <Grid item xs={12} md={12} lg={6}>
              <Box sx={{ mb: 2 }}>
                <Image layout="responsive" src={e} alt="fucking image" />
              </Box>
              <Box sx={{ mb: 2 }}>
                <Image layout="responsive" src={f} alt="fucking image" />
              </Box>
              <Box sx={{ mb: 2 }}>
                <Image layout="responsive" src={d} alt="fucking image" />
              </Box>
              <Box sx={{ mb: 2 }}>
                <Image layout="responsive" src={j} alt="fucking image" />
              </Box>
            </Grid>
          </Grid>
        </Grid>
        <Grid item sm={12} md={12} lg={5} xl={4}>
          <TradingParameters />
        </Grid>
      </Grid>
    </div>
  );
};

export default AuthComponent(Business);
